"""add_employer_verification

Revision ID: 143548b56978
Revises: 20260420_02_forum_features
Create Date: 2026-04-21 18:16:23.624242
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '143548b56978'
down_revision = '20260420_02_forum_features'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'profile_completion_percentage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('idx_applications_job_id_status', 'applications', ['job_id', 'status'], unique=False)
    op.create_index('idx_applications_user_id_status', 'applications', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_applications_applied_at'), 'applications', ['applied_at'], unique=False)
    op.create_index(op.f('ix_applications_candidate_profile_id'), 'applications', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.drop_index(op.f('idx_candidate_profiles_user_id'), table_name='candidate_profiles')
    op.drop_index(op.f('idx_candidate_skills_profile_id'), table_name='candidate_skills')
    op.create_index(op.f('ix_company_verifications_review_status'), 'company_verifications', ['review_status'], unique=False)
    op.drop_index(op.f('idx_educations_profile_id'), table_name='educations')
    op.alter_column('jobs', 'fraud_flags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index(op.f('idx_jobs_deadline_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_application_deadline'), table_name='jobs')
    op.drop_column('messages', 'is_flagged')
    op.add_column('notifications', sa.Column('job_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notifications', 'body',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('idx_notifications_user_read_created'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_entity_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_role'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.create_index(op.f('ix_notifications_job_id'), 'notifications', ['job_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'jobs', ['job_id'], ['id'])
    op.drop_column('notifications', 'message')
    op.drop_column('notifications', 'role')
    op.drop_column('notifications', 'entity_id')
    op.drop_column('notifications', 'read_at')
    op.drop_index(op.f('idx_work_experiences_profile_id'), table_name='work_experiences')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_work_experiences_profile_id'), 'work_experiences', ['profile_id'], unique=False)
    op.add_column('notifications', sa.Column('read_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('entity_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_job_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_role'), 'notifications', ['role'], unique=False)
    op.create_index(op.f('ix_notifications_read_at'), 'notifications', ['read_at'], unique=False)
    op.create_index(op.f('ix_notifications_entity_id'), 'notifications', ['entity_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('idx_notifications_user_read_created'), 'notifications', ['user_id', 'read_at', 'created_at'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('notifications', 'body',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('notifications', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'job_id')
    op.add_column('messages', sa.Column('is_flagged', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_jobs_application_deadline'), 'jobs', ['application_deadline'], unique=False)
    op.create_index(op.f('idx_jobs_deadline_status'), 'jobs', ['application_deadline', 'status'], unique=False)
    op.alter_column('jobs', 'fraud_flags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index(op.f('idx_educations_profile_id'), 'educations', ['profile_id'], unique=False)
    op.drop_index(op.f('ix_company_verifications_review_status'), table_name='company_verifications')
    op.create_index(op.f('idx_candidate_skills_profile_id'), 'candidate_skills', ['profile_id'], unique=False)
    op.create_index(op.f('idx_candidate_profiles_user_id'), 'candidate_profiles', ['user_id'], unique=False)
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_profile_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_applied_at'), table_name='applications')
    op.drop_index('idx_applications_user_id_status', table_name='applications')
    op.drop_index('idx_applications_job_id_status', table_name='applications')
    op.alter_column('applications', 'profile_completion_percentage',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
