"""Application-wide constants.
Import from here instead of hardcoding values in business logic.
"""

MATCH_SCORE_THRESHOLD = 60
SKILLS_WEIGHT = 40
EXPERIENCE_WEIGHT = 25
LOCATION_WEIGHT = 15
SALARY_WEIGHT = 20
JOB_RENEWAL_DAYS = 30
MAX_UPLOAD_SIZE_MB = 5
ALLOWED_RESUME_TYPES = [".pdf", ".docx"]
ALLOWED_IMAGE_TYPES = [".jpg", ".jpeg", ".png"]
ALERT_ENGINE_INTERVAL_HOURS = 6
NOTIFICATION_PAGE_SIZE = 20
MAX_ALERTS_PER_USER = 10
FORUM_MAX_THREADS_PER_DAY = 5
FORUM_MAX_POSTS_PER_HOUR = 15
FORUM_REPORT_AUTO_FLAG_THRESHOLD = 3
